#!zsh aliases
#alias lsd='ls -ld *(-/DN)'
alias ls='ls --color=auto -h'
alias la='ls -a'
alias lla='ls -la'
alias ll='ls -l'
alias grep='grep --color=auto '
alias ls.='ls -dF .*'
alias rezsh='exec zsh'
alias -g '^=|'
alias nocbreak=icanon
alias cal=ncal
alias tarmor2='tmux new-window -n armor2 "ssh -t green ssh -t armor2 tmux attach-session"'
alias tarmor1='tmux new-window -n armor1 "ssh -t green ssh -t armor1 tmux attach-session"'
alias t='todo.sh'
#  alias t='[[ -f ~/Dropbox/simplenote/todo.txt ]] && t $* ; [[ -f ~/Dropbox/simplenote/todo.txt ]] || ssh hurricane t $*'
# Global aliases
#alias -g M='|more'
#alias -g H='|head'
#alias -g T='|tail'
