#!zsh aliases
#alias lsd='ls -ld *(-/DN)'

#BSD ls returns failure when -h is used, easy way to distinguish a machine
#lacking gnu tools
if [ ls -h >& /dev/null ] ; then
  alias ls='ls --color=auto -h'
  alias la='ls -a'
  alias lla='ls -la'
  alias ll='ls -l'
  alias grep='grep --color=auto '
fi

alias ls.='ls -dF .*'
alias rezsh='exec zsh'
alias -g '^=|'
alias nocbreak=icanon
alias cal=ncal
alias t='todo.sh'
#  alias t='[[ -f ~/Dropbox/simplenote/todo.txt ]] && t $* ; [[ -f ~/Dropbox/simplenote/todo.txt ]] || ssh hurricane t $*'
# Global aliases
#alias -g M='|more'
#alias -g H='|head'
#alias -g T='|tail'
