#!zsh
DEFAULT_USER=njustn
[[ ! -z "$LC_TERM_PROGRAM" ]] && export TERM_PROGRAM=$LC_TERM_PROGRAM
[[ ! -z "$LC_ITERM_PROFILE" ]] && export ITERM_PROFILE=$LC_ITERM_PROFILE
[[ -f ~/.units ]] && export UNITSFILE=~/.units
LESS=-cex3MRs
ENTOMB=yes
PAGER=less
[[ -x =lesspipe.sh ]] && export LESSOPEN="|lesspipe.sh %s"
[[ -d ~/.terminfo ]] && export TERMINFO=~/.terminfo
#export TERMINFO_DIRS=~/.terminfo:/opt/local/share/terminfo
FIREFOX_OPEN_IN=tab
(( $gotroot )) && path=($path /usr/local/sbin /sbin /usr/sbin)
DATE_FMT="%c"
typeset -x LESS ENTOMB PAGER FIREFOX_OPEN_IN IRCNICK DATE_FMT
export NNTPSERVER="snews://news.purdue.edu"
export EDITOR=vim
export CVS_RSH=ssh
export LC_ALL=utf8
#[[ $TERM = "screen-256color-bce" ]] && infocmp screen-256color >& /dev/null && export TERM=screen-256color || echo screen-256color unavailable, fix it!
[[ $COLORTERM = "gnome-terminal" ]] && export TERM=xterm-256color
export GOROOT=$HOME/go
export GOARCH=amd64
export GOBIN=$HOME/programs/bin
[[ -d /usr/local/cuda ]] && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/lib
export PATH
