#!zsh
[[ -x /usr/local/bin/defaultpaths ]] && eval `/usr/local/bin/defaultpaths`
(( $gotroot )) && path=($path /usr/local/sbin /sbin /usr/sbin)
if [[ $system = darwin ]] 
then
  path=( ~/.ports/bin ~/.ports/libexec/gnubin /opt/local/libexec/gnubin /sw/bin /opt/local/bin /opt/local/sbin /Developer/usr/bin $path /usr/local/cuda/bin )
  manpath=( ~/programs/man ~/programs/share/man /opt/local/man $manpath )
  export PERL5LIB=~/programs/lib/perl5/5.8.8/darwin-2level:~/programs/lib/perl5/5.8.8:~/programs/lib/perl5/site_perl/5.8.8/darwin-2level:~/programs/lib/perl5/site_perl/5.8.8:~/programs/lib/perl5/site_perl:~/programs/lib/perl5/vendor_perl/5.8.8/darwin-2level:~/programs/lib/perl5/vendor_perl/5.8.8:~/programs/lib/perl5/vendor_perl

 test -r /sw/bin/init.sh && . /sw/bin/init.sh
fi
[[ $system = solaris ]] && path=(
	/p/zsh/bin /p/openssh/ /p/cvs/ $JAVACC/bin $CS352/bin $J2SE15/bin /usr/xpg4/bin /usr/ccs/bin $path /usr/ucb
)
[[ $domain = cs.purdue.edu ]] && path=($path /p/vim/bin) && MJ=($CS352/MJ)
path=( ~/scripts ~/programs/$bintype/bin ~/programs/bin $path /usr/local/bin /usr/bin /bin /usr/[X]{,11{,R6}}/bin(N) /usr/local/cuda/bin /usr/local/SAS/SASFoundation/9.2/bin)
typeset -U path

[[ $host = (ice[1-9]|wood[1-2]) ]] && . ~/dynamic/includes/prepare-zsh-link.sh
