#!zsh
path=(~/scripts ~/programs/$bintype/bin ~/programs/bin /usr/local/bin $path)
[[ -x /usr/local/bin/defaultpaths ]] && eval `/usr/local/bin/defaultpaths`
(( $gotroot )) && path=(/usr/local/sbin $path /sbin /usr/sbin)
if [[ $system = darwin ]] 
then

    for DIR in /opt/local/sbin /Developer/usr/bin ~/.ports/bin ~/.ports/libexec/gnubin /opt/local/libexec/gnubin /opt/local/bin
    do
        [ -d $DIR ] && path=( $DIR $path )
    done
  manpath=( ~/programs/man ~/programs/share/man /opt/local/man $manpath )
  export PERL5LIB=~/programs/lib/perl5/5.8.8/darwin-2level:~/programs/lib/perl5/5.8.8:~/programs/lib/perl5/site_perl/5.8.8/darwin-2level:~/programs/lib/perl5/site_perl/5.8.8:~/programs/lib/perl5/site_perl:~/programs/lib/perl5/vendor_perl/5.8.8/darwin-2level:~/programs/lib/perl5/vendor_perl/5.8.8:~/programs/lib/perl5/vendor_perl
  [ -x /usr/local/bin/brew ] && path=( $(brew --prefix coreutils)/libexec/gnubin /usr/local/share/python /usr/local/Cellar/ruby/1.9.3-p194/bin $path )

 test -r /sw/bin/init.sh && . /sw/bin/init.sh
fi
[[ $host = [Tt]yphoon ]] && path=( $path ~/energyware/android-sdk-macosx/tools ~/energyware/android-sdk-macosx/platform-tools )
[[ $system = solaris ]] && path=(
	/p/zsh/bin /p/openssh/ /p/cvs/ $JAVACC/bin $CS352/bin $J2SE15/bin /usr/xpg4/bin /usr/ccs/bin $path /usr/ucb
)
[[ $domain = cs.purdue.edu ]] && path=($path /p/vim/bin) && MJ=($CS352/MJ)
path=(  $path /usr/bin /bin /usr/[X]{,11{,R6}}/bin(N) /usr/local/cuda/bin )
#/usr/local/SAS/SASFoundation/9.2/bin)
typeset -U path

[[ $host = (ice[1-9]|wood[1-2]) ]] && . ~/dynamic/includes/prepare-zsh-link.sh

[[ -d '/opt/pgi/osx86-64/11.10/bin' ]] && path=( $path /opt/pgi/osx86-64/11.10/bin )

