#!zsh
local -a oldpath
local POSIXPATH
local -x POSIXLY_CORRECT=1 CMD_ENV=xpg4 PS_PERSONALITY=posix
local -x _XPG=1 UNIX95=1 POSIX_ME_HARDER=1 LC_ALL=POSIX
local -x BLOCK_SIZE=512 DF_BLOCK_SIZE=512 DU_BLOCK_SIZE=512
local -x LS_BLOCK_SIZE=1
oldpath=($path)
path=(/usr/xpg4/bin /bin /usr/bin $path)
if getconf PATH | read POSIXPATH 
PATH=$POSIXPATH:$PATH
command $@
path=($oldpath)
