(setq user-init-file (or load-file-name (buffer-file-name)))
(setq user-emacs-directory (file-name-directory user-init-file))
(if (not (getenv "DOOMLOCALDIR"))
  (setenv "DOOMLOCALDIR" "~/.cache/doom-local"))
(if (not (getenv "DOOMDIR"))
  (setenv "DOOMDIR" "~/.dotfiles/doom"))
