#!/usr/bin/env zsh

if (( $+commands[delta] )) ; then
  args=(
    --theme Dracula
  )
    #--relative-paths
    #--navigate
    #--line-numbers
  # --hyperlinks # removed because of alacritty and winTerm, no support yet
  if [[ $(tput cols) -gt 160 ]] ; then
    args+="--side-by-side"
  fi
  exec delta $args "$@"
else
  $PAGER "$@"
fi
