#!/bin/sh

# receives filename as only argument, writes replacement, echos new filename to
# stdout

if which batcat > /dev/null 2>&1 ; then
    BAT=batcat
else
    BAT=bat
fi
export BAT_STYLE=plain
${BAT} --pager never --color always --decorations always "$1" > /tmp/lessopen-bat.$$
echo /tmp/lessopen-bat.$$

