#!/usr/bin/env zsh

if (( ${+commands[asdf]} )) ; then
  if [[ -d ~/.cache/asdf/installs/neovim ]] ; then
    exec asdf exec nvim "$@"
  fi
fi

# if (( $+commands[snap] )) ; then
#   if snap run nvim --version &> /dev/null ; then
#     exec snap run nvim "$@"
#   fi
# fi

if (( $+commands[nvim] )) ; then
  exec nvim "$@"
fi

#remove self
path=("${(@)path:#~/scripts}")
exec vim "$@"
