#!zsh aliases

autoload -U regexp-replace
setopt re_match_pcre

# alias bd='mkbdir -p'
# alias cdb='cd $(mkbdir -p)'
# alias cdp='cd $(mkbdir -pr)'
# alias makeb='make -C $(mkbdir -p)'

if which srun >& /dev/null  ; then
    alias sr1='srun -N 1 --exclusive --pty'
    alias sr4='srun -N 4 --exclusive --pty'
fi

alias ls.='ls -dF .*'

alias grep='grep --color=auto '
alias rezsh='exec zsh'
alias -g '^=|'
alias nocbreak=icanon
alias cal=ncal
# alias t='todo.sh'
#  alias t='[[ -f ~/Dropbox/simplenote/todo.txt ]] && t $* ; [[ -f ~/Dropbox/simplenote/todo.txt ]] || ssh hurricane t $*'
# Global aliases
#alias -g M='|more'
#alias -g H='|head'
#alias -g T='|tail'

alias rm=""${${aliases[rm]:-rm -I}:s/-i/-I/}""

# fasd aliases
alias v="f -e vim"
command -v open > /dev/null && alias o='f -e xdg-open' || alias o="f -e open" 

#IMPORTED
# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# additional docker alias for normal run command
alias dkrit='docker run --rm -it -v $(pwd):/curdir -w /curdir'

if hub >& /dev/null ; then
    alias git='noglob hub'
else
    alias git='noglob git'
fi

alias git-branch-current="git branch --show-current"
alias gbsc="git branch --show-current"
alias g="git"
function gRuo() {
    local origin=($(git remote -v | grep '^origin'))
    local upstream=($(git remote -v | grep '^upstream'))
    local origin_s="${origin[2]}"
    local new_origin="${origin[2]}"
    if [[ $new_origin =~ https://.* ]] ; then
        echo "$new_origin"
        new_origin=$(echo $new_origin | sed -e 's|https://|git@|' -e 's|/|:|')
    else
    fi
    local user=trws
    if [[ $new_origin =~ llnl ]] ; then
        user=scogland
    fi
    regexp-replace new_origin ':[^/]+?/' ":$user/"
    echo "Change origin from ${origin_s} to $new_origin?"
    local q
    read -q q
    if [[ $q == y ]] ; then
        echo
        if git remote show upstream >& /dev/null ; then
            echo "$upstream already exists, replace?"
            read -q q
            if [[ $q == n ]] ; then
                return
            fi
            git remote remove upstream
        fi
        git remote rename origin upstream
        git remote add origin "$new_origin"
        echo Done
    fi
    # git remote rename origin upstream
}
alias gfu="git fetch upstream"
alias grum="git rebase upstream/master"
alias gpoc='git push origin $(git rev-parse --abbrev-ref HEAD)'
alias gpocf='git push origin -f $(git rev-parse --abbrev-ref HEAD)'
alias h="history"
alias j="jobs"

# List all files colorized in long format
alias l="ls -lF "

# List all files colorized in long format, including dot files
alias la="ls -laF "

# List only directories
alias lsd="ls -lF | grep --color=never '^d'"

# Enable aliases to be sudo’ed, removed, prefer having nocorrect etc. and
# completion work to having aliases expand and break on them
# alias sudo='sudo '

# Get week number
alias week='date +%V'

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# Get OS X Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm update npm -g; npm update -g; sudo gem update --system; sudo gem update'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

command -v open > /dev/null || alias open=xdg-open
# Canonical hex dump; some systems have this symlinked
command -v hd > /dev/null || alias hd="hexdump -C"

# OS X has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# OS X has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# JavaScriptCore REPL
jscbin="/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc";
[ -e "${jscbin}" ] && alias jsc="${jscbin}";
unset jscbin;

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Merge PDF files
# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'

# Disable Spotlight
alias spotoff="sudo mdutil -a -i off"
# Enable Spotlight
alias spoton="sudo mdutil -a -i on"

# PlistBuddy alias, because sometimes `defaults` just doesn’t cut it
alias plistbuddy="/usr/libexec/PlistBuddy"

# Ring the terminal bell, and put a badge on Terminal.app’s Dock icon
# (useful when executing time-consuming commands)
alias badge="tput bel"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  alias "$method"="lwp-request -m '$method'"
done

# Make Grunt print stack traces by default
command -v grunt > /dev/null && alias grunt="grunt --stack"

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume 7'"

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

# Faster npm for Europeans
command -v npm > /dev/null && alias npme="npm --registry http://registry.npmjs.eu/"
