#!zsh bindings
bindkey -me >& /dev/null

# Turn off the stop key binding
# NOTE: checks here to ensure ssty only applies to a real tty
# https://github.com/sorin-ionescu/prezto/pull/1771/files
[[ -n ${TTY:-} && $+commands[stty] == 1 ]] && stty -ixon <$TTY >$TTY

bindkey '[3~' delete-char
bindkey '[4~' end-of-line
bindkey '[1~' beginning-of-line
bindkey 'OH' beginning-of-line
bindkey 'OF' end-of-line
bindkey '[H' beginning-of-line
bindkey '[F' end-of-line
bindkey '[1;3D' beginning-of-line
bindkey '[1;3C' end-of-line
bindkey '[1;9C' forward-word
bindkey '[1;9D' backward-word

### Jetbrains terminal
if [[ "$TERMINAL_EMULATOR" == "JetBrains-JediTerm" ]]; then
  bindkey -s "µ" "^E | less ^M" # Personal Alt-M shortcut
  bindkey "ƒ" forward-word
  bindkey "∫" backward-word
  bindkey "∂" kill-word
  bindkey "¬" downcase-word
  bindkey "ç" capitalize-word
  bindkey "†" transpose-words
  bindkey "≥" insert-last-word
  # bindkey "¨ " upcase-word
fi
