#!zsh
DEFAULT_USER=njustn

export GIT_AUTHOR_NAME='Tom Scogland'
export GIT_AUTHOR_EMAIL=scogland1@llnl.gov
export GIT_COMMITTER_NAME='Tom Scogland'
export GIT_COMMITTER_EMAIL=scogland1@llnl.gov
export GITHUB_USER=trws
[[ -e ~/scripts/ssh ]] && export GIT_SSH_COMMAND=~/scripts/ssh


# Give global tags an exuberant ctags backend
# [[ -e ~/.globalrc ]] && export GTAGSCONF=~/.globalrc
export MAKEOBJDIRPREFIX=~/.cache/global-obj
export GTAGS_OPTIONS='-O --gtagslabel ctags'
export GTAGSLIBPATH=/opt/local/include:/usr/local/include:/usr/include:/Developer/Headers:~/programs/include

# handle sending iterm info across SSH, yay for LC_*
[[ ! -z "$LC_TERM_PROGRAM" ]] && export TERM_PROGRAM=$LC_TERM_PROGRAM
[[ ! -z "$LC_ITERM_PROFILE" ]] && export ITERM_PROFILE=$LC_ITERM_PROFILE
[[ -z "$LC_TERM_PROGRAM" ]] && export LC_TERM_PROGRAM=$TERM_PROGRAM
[[ -z "$LC_ITERM_PROFILE" ]] && export LC_ITERM_PROFILE=$ITERM_PROFILE
[[ -f ~/.units ]] && export UNITSFILE=~/.units

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

ENTOMB=yes

if (( $+commands[fzf] )) ; then
  if (( $+commands[fd] )) ; then
    export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
  elif (( $+commands[pt] )) ; then
    export FZF_DEFAULT_COMMAND='pt --follow --nocolor --nogroup -g=.'
  fi
fi

export EDITOR=vim
export VISUAL=vim

if (( $+commands[vimpager] )) ; then
  PAGER=vimpager
else
  PAGER=less
fi

if (( $+commands[rg] )) ; then
  export FZF_DEFAULT_COMMAND='rg --files'
elif (( $+commands[fd] )) ; then
  export FZF_DEFAULT_COMMAND='fd --type f'
fi

[[ -e ~/.pystartup ]] && export PYTHONSTARTUP=$HOME/.pystartup

[[ -d ~/.terminfo ]] && export TERMINFO=~/.terminfo

(( $gotroot )) && path=($path /usr/local/sbin /sbin /usr/sbin)
DATE_FMT="%c"
typeset -x LESS ENTOMB PAGER DATE_FMT

export CVS_RSH=ssh
export LANG=en_US.UTF-8

[[ $COLORTERM = "gnome-terminal" ]] && export TERM=xterm-256color

[[ -d /usr/local/cuda ]] && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/lib

export PATH
[[ -e ~/.ssh/github_oauth ]] && export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.ssh/github_oauth)

export OMP_NESTED=true
export OMP_MAX_ACTIVE_LEVELS=5
