#!zsh
DEFAULT_USER=njustn

export GIT_AUTHOR_NAME='Tom Scogland'
export GIT_AUTHOR_EMAIL=scogland1@llnl.gov
export GITHUB_USER=trws

[[ -f ~/perl5/perlbrew/etc/bashrc ]] && source ~/perl5/perlbrew/etc/bashrc

[[ ! -z "$LC_TERM_PROGRAM" ]] && export TERM_PROGRAM=$LC_TERM_PROGRAM && unset LC_TERM_PROGRAM
[[ ! -z "$LC_ITERM_PROFILE" ]] && export ITERM_PROFILE=$LC_ITERM_PROFILE  && unset LC_ITERM_PROFILE
[[ -f ~/.units ]] && export UNITSFILE=~/.units
LESS=-cex3MRs
ENTOMB=yes
PAGER=less
[[ -x =lesspipe.sh ]] && export LESSOPEN="|lesspipe.sh %s"
[[ -d ~/.terminfo ]] && export TERMINFO=~/.terminfo
[[ -d ~/build/clang ]] && export PYTHONPATH=~/build/clang/llvm/tools/clang/bindings/python:$PYTHONPATH
[[ -d ~/build/clang ]] && export LD_LIBRARY_PATH=$(~/build/clang/install/bin/llvm-config --libdir):$LD_LIBRARY_PATH
#export TERMINFO_DIRS=~/.terminfo:/opt/local/share/terminfo
FIREFOX_OPEN_IN=tab
(( $gotroot )) && path=($path /usr/local/sbin /sbin /usr/sbin)
DATE_FMT="%c"
typeset -x LESS ENTOMB PAGER FIREFOX_OPEN_IN IRCNICK DATE_FMT
export NNTPSERVER="snews://news.purdue.edu"
export EDITOR=vim
export CVS_RSH=ssh
export LC_ALL=en_US.UTF-8
#[[ $TERM = "screen-256color-bce" ]] && infocmp screen-256color >& /dev/null && export TERM=screen-256color || echo screen-256color unavailable, fix it!
[[ $COLORTERM = "gnome-terminal" ]] && export TERM=xterm-256color
export GOROOT=/usr/local/opt/go/libexec
# export GOARCH=amd64
export GOBIN=/usr/local/go/bin
export GOPATH=~/go
[[ -d /usr/local/cuda ]] && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/lib
export PATH
export HOMEBREW_GITHUB_API_TOKEN=e68741bb043902338ab33f78f8f88da573f66e6a
export OMP_NESTED=true
export OMP_MAX_ACTIVE_LEVELS=5
