#!zsh
DEFAULT_USER=njustn

export GIT_AUTHOR_NAME='Tom Scogland'
export GIT_AUTHOR_EMAIL=scogland1@llnl.gov
export GIT_COMMITTER_NAME='Tom Scogland'
export GIT_COMMITTER_EMAIL=scogland1@llnl.gov
export GITHUB_USER=trws
[[ -e ~/scripts/ssh ]] && export GIT_SSH_COMMAND=~/scripts/ssh


# Give global tags an exuberant ctags backend
# [[ -e ~/.globalrc ]] && export GTAGSCONF=~/.globalrc
export MAKEOBJDIRPREFIX=~/.cache/global-obj
export GTAGS_OPTIONS='-O --gtagslabel ctags'
export GTAGSLIBPATH=/opt/local/include:/usr/local/include:/usr/include:/Developer/Headers:~/programs/include

# handle sending iterm info across SSH, yay for LC_*
[[ ! -z "$LC_TERM_PROGRAM" ]] && export TERM_PROGRAM=$LC_TERM_PROGRAM
[[ ! -z "$LC_ITERM_PROFILE" ]] && export ITERM_PROFILE=$LC_ITERM_PROFILE
[[ -z "$LC_TERM_PROGRAM" ]] && export LC_TERM_PROGRAM=$TERM_PROGRAM
[[ -z "$LC_ITERM_PROFILE" ]] && export LC_ITERM_PROFILE=$ITERM_PROFILE

ENTOMB=yes

if (( $+commands[fd] )) ; then
  export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
  export FZF_ALL_FILES_COMMAND='fd --type f --hidden --no-ignore --follow --exclude .git'
elif (( $+commands[rg] )) ; then
  export FZF_DEFAULT_COMMAND='rg --files'
  export FZF_ALL_FILES_COMMAND='rg --files --no-ignore'
fi

export DOOMLOCALDIR="~/.cache/doom-local/"
export DOOMDIR="~/.dotfiles/doom/"

VIM=vim
GIVM=vim
if (( $+commands[nvim] )) ; then
  VIM=nvim
fi
if (( $+commands[vimr] )) ; then
  GVIM=vimr
elif (( $+commands[mvim] )) ; then
  GVIM=mvim
elif (( $+commands[gvim] )) ; then
  GVIM=gvim
fi

export EDITOR="$VIM"
export VISUAL="$VIM"
export VIMPAGER_VIM="$VIM"

# set up homebrew nvm
# switching to asdf for now, will see
# export NVM_DIR="$HOME/.nvm"
# [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
# [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-i -M -R -w -z-4' # maybe restore -F -X
export LESSOPEN="lessopen-bat %s"
export BAT_PAGER="less -L $LESS" # -L avoids LESSOPEN being interpreted, no loops

alias vman="env -u MANPAGER man"
if (( $+commands[bat] )) ; then
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
elif (( $+commands[vimpager] )) ; then
  export MANPAGER=vimpager

fi

PAGER=less

[[ -e ~/.pystartup ]] && export PYTHONSTARTUP=$HOME/.pystartup

[[ -d ~/.terminfo ]] && export TERMINFO=~/.terminfo

(( $gotroot )) && path=($path /usr/local/sbin /sbin /usr/sbin)
DATE_FMT="%c"
typeset -x LESS ENTOMB PAGER DATE_FMT

export CVS_RSH=ssh
export LANG=en_US.UTF-8

if [[ $TERM = iterm2-direct ]] ; then
  export COLORTERM=truecolor
elif [[ $TERM = "tmux" ]] ; then
  export TERM=tmux-256color
elif [[ $COLORTERM = "gnome-terminal" ]] ; then
  export TERM=xterm-256color
fi

[[ -d /usr/local/cuda ]] && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/lib

export PATH
[[ -e ~/.ssh/github_oauth ]] && export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.ssh/github_oauth)

export OMP_NESTED=true
export OMP_MAX_ACTIVE_LEVELS=5
