#!zsh

#pack configuration variables I want

export LC_ITERM_PROFILE=$ITERM_PROFILE
export LC_TERM_PROGRAM=$TERM_PROGRAM

#CONFIGS=$HOME/.ssh/config
CONFIGS=''

if [[ $system = darwin  && -x /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport ]]
then
    if [[ -n $(arp -a | grep -e '0:15:17:14:d6:96' -e '0:16:cb:c5:ff:3a') ]]
    then
        CONFIGS=($CONFIGS $HOME/Dropbox/config/ssh_synergy)
    else
        CONFIGS=($CONFIGS $HOME/Dropbox/config/ssh_synergy_away)
    fi
    if [[ -n $(arp -a | grep -e '90:84:d:d4:18:46' ) ]]
    then
        CONFIGS=($CONFIGS $HOME/Dropbox/config/ssh_ether)
    else
        CONFIGS=($CONFIGS $HOME/Dropbox/config/ssh_ether_away)
    fi
fi

#  echo $CONFIGS

if [[ -n "$CONFIGS" ]]
then
    TMPFILE=$(mktemp '/tmp/ssh_config.XXXX')
    awk 'NR==1{p=1};p;/CUT_HERE/{p=0}' ~/.ssh/config > $TMPFILE
    cat $CONFIGS >> $TMPFILE
    #cat $TMPFILE

    command /usr/bin/ssh -F $TMPFILE $@
else
    command /usr/bin/ssh $@
fi

rm -f $TMPFILE
